name: heatstroke_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  circle_ui_navigator: ^1.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  geolocator: ^12.0.0
  http: ^1.2.1
  intl: ^0.19.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

fonts:
  - family: Poppins
    fonts:
      - assets/Poppins-Black.ttf
      - assets/Poppins-Bold.ttf
      - assets/Poppins-Light.ttf
      - assets/Poppins-Medium.ttf
      - assets/Poppins-Regular.ttf
      - assets/Poppins-Thin.ttf
